# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      midi-file:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'the midi file'
        # Default value if no value is explicitly provided
        default: 'song.mid'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Install Package
      # You may pin to the exact commit or the version.
      # uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30
      uses: ConorMacBride/install-package@v1.1.0
      with:
        # Packages to install with brew on macOS
#         brew: # optional, default is 
        # Packages to install with brew cask on macOS
#         brew-cask: # optional, default is 
        # Packages to install with apt on Linux
        apt: timidity ffmpeg fish  # optional, default is 
        # Packages to install with choco on Windows
#         choco: # optional, default is 
    - name: generate mp3
      run: ./midi-to-mp3.fish ${{ github.event.inputs.midi-file }} ${{ github.event.inputs.midi-file }}.mp3  #echo "Hello ${{ github.event.inputs.name }}"
